/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.shitikov.task13;

import org.apache.commons.lang3.math.NumberUtils;

public class StringUtils {
    public boolean isPositiveNumber(String str) throws NotNumberException {
        if (NumberUtils.isCreatable(str)) {
            double numb = NumberUtils.toDouble(str);
            return numb > 0;
        } else {
            throw new NotNumberException("This string isn't number");
        }
    }
}
